-- Miselium Operations - Weekly recurring tasks
-- Adds a second "kind" of task alongside project tasks: an operational task
-- that repeats every week on a given weekday (revisar pendientes, seguimiento
-- de clientes, reporte semanal, respaldos, etc.) without a project attached
-- by default. Two tables:
--
--   recurring_tasks            the template/config (one row per recurrence)
--   recurring_task_occurrences materialized status OVERRIDES only - not one
--                               row per week forever
--
-- ===== Duplicate-avoidance strategy (read this before touching the frontend) =====
-- There is no server/cron here (same $0-infra constraint as the rest of this
-- app - see 005_agency_features.sql's "due soon notifications" note), so
-- occurrences for future weeks are never pre-generated by a background job.
-- Instead:
--   - which dates *would* have an occurrence for a given recurring_tasks row
--     is pure date arithmetic in the frontend (matching weekday, inside
--     [start_date, end_date or infinity], active = true) - see
--     src/lib/recurringDates.ts. No DB row is needed for a still-pending
--     occurrence; PENDING is the implicit default for any date that matches
--     but has no row here.
--   - a row in this table is only created once someone changes an
--     occurrence's status away from the implicit default (IN_PROGRESS / DONE
--     / SKIPPED), via an upsert on (recurring_task_id, occurrence_date) -
--     `insert ... on conflict (recurring_task_id, occurrence_date) do
--     update`. The unique constraint below is what makes that upsert safe to
--     call repeatedly (e.g. revisiting the same week twice) without ever
--     creating a duplicate row.
--
-- ===== Week boundary =====
-- Monday-Sunday (ISO week), matching the existing "disponibilidad de lunes a
-- sabado" convention on Team.tsx / profiles.daily_available_hours, and
-- Team.tsx's own startOfWeek() helper (Monday-based). `weekday` is stored as
-- a 3-letter text code (MON..SUN) rather than a raw 0-6 int, matching this
-- codebase's existing style of text-based checked enums (tasks.status,
-- tasks.priority, projects.status) over raw integers.

-- ===== recurring_tasks =====
create table if not exists public.recurring_tasks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id),
  name text not null,
  description text,
  assignee_id uuid references public.profiles(id) on delete set null,
  weekday text not null check (weekday in ('MON','TUE','WED','THU','FRI','SAT','SUN')),
  time_of_day time,
  estimated_hours numeric(5,2) check (estimated_hours is null or estimated_hours >= 0),
  priority text not null default 'MEDIUM' check (priority in ('LOW','MEDIUM','HIGH')),
  category text,
  client_id uuid references public.clients(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  start_date date not null default current_date,
  end_date date,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recurring_tasks_end_after_start check (end_date is null or end_date >= start_date)
);
create index if not exists idx_recurring_tasks_organization_id on public.recurring_tasks(organization_id);
create index if not exists idx_recurring_tasks_assignee_id on public.recurring_tasks(assignee_id);
create index if not exists idx_recurring_tasks_weekday on public.recurring_tasks(weekday);
create index if not exists idx_recurring_tasks_client_id on public.recurring_tasks(client_id);
create index if not exists idx_recurring_tasks_project_id on public.recurring_tasks(project_id);

drop trigger if exists trg_recurring_tasks_updated_at on public.recurring_tasks;
create trigger trg_recurring_tasks_updated_at
before update on public.recurring_tasks
for each row execute function public.set_updated_at();

-- ===== recurring_task_occurrences =====
create table if not exists public.recurring_task_occurrences (
  id uuid primary key default gen_random_uuid(),
  recurring_task_id uuid not null references public.recurring_tasks(id) on delete cascade,
  occurrence_date date not null,
  status text not null default 'PENDING' check (status in ('PENDING','IN_PROGRESS','DONE','SKIPPED')),
  completed_at timestamptz,
  completed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recurring_task_occurrences_unique unique (recurring_task_id, occurrence_date)
);
create index if not exists idx_rt_occurrences_recurring_task_id on public.recurring_task_occurrences(recurring_task_id);
create index if not exists idx_rt_occurrences_occurrence_date on public.recurring_task_occurrences(occurrence_date);

drop trigger if exists trg_rt_occurrences_updated_at on public.recurring_task_occurrences;
create trigger trg_rt_occurrences_updated_at
before update on public.recurring_task_occurrences
for each row execute function public.set_updated_at();

-- ===== RLS helpers =====
-- Same style as is_project_in_org() / is_task_assignee() in 008_org_scoped_rls.sql
-- / 005_agency_features.sql: security definer so they aren't themselves gated
-- by the RLS of the table they check.
create or replace function public.is_recurring_task_in_org(p_recurring_task_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.recurring_tasks rt
    where rt.id = p_recurring_task_id and rt.organization_id = public.current_org_id()
  );
$$;

create or replace function public.is_recurring_task_assignee(p_recurring_task_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.recurring_tasks rt
    where rt.id = p_recurring_task_id and rt.assignee_id = auth.uid()
  );
$$;

-- ===== recurring_tasks RLS =====
-- SELECT: anyone in the org (COLLABORATOR needs to see the config - name,
-- day, time - to know what's expected of them, matching how tasks_select
-- lets a COLLABORATOR see task rows too). INSERT/UPDATE/DELETE: ADMIN or
-- PROJECT_MANAGER only, same "can manage content" tier as clients/projects/
-- tasks - a COLLABORATOR can look but not touch the recurrence config.
alter table public.recurring_tasks enable row level security;

drop policy if exists recurring_tasks_select on public.recurring_tasks;
create policy recurring_tasks_select on public.recurring_tasks
  for select using (organization_id = public.current_org_id());

drop policy if exists recurring_tasks_insert on public.recurring_tasks;
create policy recurring_tasks_insert on public.recurring_tasks
  for insert with check (
    public.current_role_is_admin_or_pm() and organization_id = public.current_org_id()
  );

drop policy if exists recurring_tasks_update on public.recurring_tasks;
create policy recurring_tasks_update on public.recurring_tasks
  for update using (
    public.current_role_is_admin_or_pm() and organization_id = public.current_org_id()
  )
  with check (
    public.current_role_is_admin_or_pm() and organization_id = public.current_org_id()
  );

drop policy if exists recurring_tasks_delete on public.recurring_tasks;
create policy recurring_tasks_delete on public.recurring_tasks
  for delete using (
    public.current_role_is_admin_or_pm() and organization_id = public.current_org_id()
  );

-- ===== recurring_task_occurrences RLS =====
-- SELECT: scoped via the parent recurring_tasks row's organization (same
-- pattern as time_entries/task_comments joining up through tasks ->
-- projects). INSERT/UPDATE (the upsert used to change an occurrence's
-- status): ADMIN/PM of the org, OR the COLLABORATOR who is the parent
-- recurring_tasks row's assignee - completing/skipping their own occurrence
-- is fine, completing someone else's is not, and neither can touch the
-- recurring_tasks config itself (that's a separate table/policy above).
-- DELETE: ADMIN/PM only. "Eliminar solo futuras ocurrencias" (see the
-- two-option delete flow in the UI) is implemented by setting the parent
-- recurring_tasks.end_date to yesterday, NOT by deleting rows here - past
-- history (completed/skipped occurrences) must never be silently destroyed
-- by that option. A literal DELETE on this table is only ever used for the
-- "eliminar completamente" option, which cascades via the recurring_tasks FK
-- instead of deleting occurrence rows directly.
alter table public.recurring_task_occurrences enable row level security;

drop policy if exists rt_occurrences_select on public.recurring_task_occurrences;
create policy rt_occurrences_select on public.recurring_task_occurrences
  for select using (public.is_recurring_task_in_org(recurring_task_id));

drop policy if exists rt_occurrences_insert on public.recurring_task_occurrences;
create policy rt_occurrences_insert on public.recurring_task_occurrences
  for insert with check (
    public.is_recurring_task_in_org(recurring_task_id)
    and (
      public.current_role_is_admin_or_pm()
      or public.is_recurring_task_assignee(recurring_task_id)
    )
  );

drop policy if exists rt_occurrences_update on public.recurring_task_occurrences;
create policy rt_occurrences_update on public.recurring_task_occurrences
  for update using (
    public.is_recurring_task_in_org(recurring_task_id)
    and (
      public.current_role_is_admin_or_pm()
      or public.is_recurring_task_assignee(recurring_task_id)
    )
  )
  with check (
    public.is_recurring_task_in_org(recurring_task_id)
    and (
      public.current_role_is_admin_or_pm()
      or public.is_recurring_task_assignee(recurring_task_id)
    )
  );

drop policy if exists rt_occurrences_delete on public.recurring_task_occurrences;
create policy rt_occurrences_delete on public.recurring_task_occurrences
  for delete using (
    public.current_role_is_admin_or_pm() and public.is_recurring_task_in_org(recurring_task_id)
  );
